### ISSUE TITLE
v1.4.3 - Cannot find module './tsc-dist/main'

### ISSUE THREAD

**Issue by duritong** [flathub/chat.delta.desktop#41]
After updating from 1.3.2 to 

```
$ flatpak list | grep chat.delta.desktop
Delta Chat	chat.delta.desktop	v1.4.3	stable	system
```

I can't run the flatpak anymore:

```
$ flatpak run --verbose chat.delta.desktop 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/duritong/.local/share/flatpak
F: Opening user flatpak installation at path /home/duritong/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/duritong/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1233070781
F: Allocated instance id 1143068101
F: Add defaults in dir /chat/delta/desktop/
F: Add locks in dir /chat/delta/desktop/
F: Allowing homedir access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/duritong/.config/pulse/client.conf': Error opening file /home/duritong/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
F: Running 'bwrap --args 34 /app/bin/run.sh'
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './tsc-dist/main'
Require stack:
- /app/delta/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/app/delta/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/app/delta/resources/app.asar/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
^C
```

I need to abort the running process afterwards, but deltachat is never started.

If I kill the deltachat-desktop app process, I additionally, get:

```
$ flatpak run chat.delta.desktop 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './tsc-dist/main'
Require stack:
- /app/delta/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/app/delta/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/app/delta/resources/app.asar/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
$
```

**Comment by muelli** [comment]
yep. I reverted the update. 1.4.2 doesn't work either.

**Comment by Simon-Laux** [comment]
@muelli don't forget to run `npm run build` or `npm run build4production`. Looks like this went missing as `npm run pack`doesn't include the build step like `npm run dist` did.

**Comment by muelli** [comment]
can you tell me what commands need to be run, in what order, in order to get the app in a state that we can run it? Bonus points, if you arrange the commands in the manifest, cf. https://github.com/flathub/chat.delta.desktop/pull/40/files#diff-5a918bacb13ca69f745f64af712b3e60L49

**Comment by Simon-Laux** [comment]
the steps are bassicly
clone
npm install
npm run build4production
npm run pack:generate_config --offline --verbose
npm run pack:linux:dir --offline --verbose

in this case `npm run build4production` is missing between install and pack

**Comment by muelli** [comment]
@duritong can you try the beta?

**Comment by duritong** [comment]
The beta flatpak works fine for me for now. Thank you a lot!
